version: "3.9"
   
services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}  
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
  web:
    build: 
      context: .
      args:
        DATABASE_NAME: ${DATABASE_NAME}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}  
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_PORT: ${DATABASE_PORT}  
        DATABASE_USER: ${DATABASE_USER}  
        EMAIL_USER: ${EMAIL_USER}  
        EMAIL_PASS: ${EMAIL_PASS}  
        DEBUG: ${DEBUG}  
    volumes:
      - .:/code
      - type: bind
        source: $HOST/home/cloud-user/certs
        targhet: /certs
    ports:
      - "8000:8000"
      - "80:80"
      - "443:443"
    links:
      - db