FROM python:3
ARG DATABASE_NAME
ARG DATABASE_NAME $DATABASE_NAME
ARG DATABASE_PASSWORD $DATABASE_PASSWORD
ARG DATABASE_HOST $DATABASE_HOST
ARG DATABASE_PORT $DATABASE_PORT
ARG DATABASE_USER $DATABASE_USER
ARG EMAIL_USER $EMAIL_USER
ARG EMAIL_PASS $EMAIL_PASS
ARG DEBUG $DEBUG
ENV PYTHONUNBUFFERED=1
ENV DATABASE_NAME $DATABASE_NAME
ENV DATABASE_PASSWORD $DbATABASE_PASSWORD
ENV DATABASE_HOST $DATABASE_HOST
ENV DATABASE_PORT $DATABASE_PORT
ENV DATABASE_USER $DATABASE_USER
ENV EMAIL_USER $EMAIL_USER
ENV EMAIL_PASS $EMAIL_PASS
ENV DEBUG $DEBUG
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
RUN apt-get update && \
    apt install -y openjdk-11-jre-headless

RUN export JAVA_HOME
COPY . /code/