# Generated by Django 3.1.6 on 2021-03-10 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdf', max_length=1000)),
                ('filename', models.CharField(max_length=1000)),
                ('size', models.IntegerField()),
                ('pagecount', models.IntegerField()),
                ('sha1sum', models.CharField(max_length=40, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'doc_pdf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.pdf')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doc_owner',
                'managed': True,
                'unique_together': {('document', 'owner')},
            },
        ),
    ]
