# Generated by Django 3.1.6 on 2021-04-28 06:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20210425_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ImageMagick', 'Imagemagick'), ('Tesseract_OCR', 'Tesseract Ocr'), ('Tesseract_DB', 'Tesseract Db')], max_length=32)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Running', 'Running'), ('Finished', 'Finished')], max_length=32)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.pdf')),
            ],
            options={
                'db_table': 'doc_task',
                'managed': True,
            },
        ),
    ]
