# Generated by Django 3.1.5 on 2021-05-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20210504_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='issue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='journal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='pages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
