# Generated by Django 3.1.7 on 2021-02-21 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SourceField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_order', models.IntegerField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.source')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SourceValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('source_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.sourcefield')),
            ],
        ),
        migrations.CreateModel(
            name='SourceEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.source')),
            ],
        ),
        migrations.CreateModel(
            name='SourceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.sourceentity')),
                ('source_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.sourcefield')),
                ('source_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.sourcevalue')),
            ],
        ),
    ]
