# Generated by Django 3.1.6 on 2021-03-10 03:43

# empy created first with command:
# python manage.py makemigrations --empty tesserakti
# täytyy ilmeisesti ajaa näin omassa migraatiossaan koska taulut ei vielä luotu ensimmäisessä.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesserakti', '0001_initial'),
    ]

    operations = [
        # https://docs.djangoproject.com/en/3.1/ref/migration-operations/
        migrations.RunSQL(
            sql="""            
ALTER TABLE tes_page ADD CONSTRAINT tes_page_fk FOREIGN KEY tes_page (document_id) REFERENCES pdf_document (id) ;
ALTER TABLE tes_block ADD CONSTRAINT tes_block_fk FOREIGN KEY tes_block (page_id, document_id) REFERENCES tes_page(page_id, document_id);
ALTER TABLE tes_paragraph ADD CONSTRAINT tes_paragraph_fk FOREIGN KEY (block_id, page_id, document_id) REFERENCES tes_block(block_id, page_id, document_id);
ALTER TABLE tes_line ADD CONSTRAINT tes_line_fk FOREIGN KEY (paragraph_id, block_id, page_id, document_id) REFERENCES tes_paragraph(paragraph_id, block_id, page_id, document_id);
ALTER TABLE tes_word ADD CONSTRAINT tes_word_fk FOREIGN KEY (line_id, paragraph_id, block_id, page_id, document_id) REFERENCES tes_line(line_id, paragraph_id, block_id, page_id, document_id);
            """,
            reverse_sql="""
ALTER TABLE tes_page DROP CONSTRAINT tes_page_fk;
ALTER TABLE tes_block DROP CONSTRAINT tes_block_fk;
ALTER TABLE tes_paragraph DROP CONSTRAINT tes_paragrahp_fk;
ALTER TABLE tes_line DROP CONSTRAINT tes_line_fk;
ALTER TABLE tes_word DROP CONSTRAINT tes_word_fk;
            """
        )
    ]
