# Generated by Django 3.1.7 on 2021-04-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traittable',
            name='verbatimTraitUnit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
