# Generated by Django 3.1.1 on 2021-03-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('citation', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='media/pdfs/')),
            ],
        ),
        migrations.DeleteModel(
            name='PageView',
        ),
    ]
