# Generated by Django 3.1.6 on 2021-04-25 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('project', '0002_auto_20210417_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traittable',
            name='pdf_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.pdf'),
        ),
        migrations.DeleteModel(
            name='Pdf',
        ),
    ]
