# Generated by Django 3.1.1 on 2021-03-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210315_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='citation',
            new_name='author',
        ),
    ]
