# Generated by Django 3.1.7 on 2021-03-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210315_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
