# Generated by Django 3.1.7 on 2021-03-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Json_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_table', models.JSONField()),
                ('table', models.FileField(upload_to='json/')),
            ],
        ),
    ]
