# Generated by Django 3.1.7 on 2021-04-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Json_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('pdf_id', models.IntegerField(null=True)),
                ('page_number', models.IntegerField(null=True)),
                ('table_num', models.IntegerField(null=True)),
                ('json_table', models.JSONField()),
                ('table', models.FileField(max_length=500, upload_to='json/')),
            ],
        ),
        migrations.CreateModel(
            name='Trait_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_id', models.IntegerField(null=True)),
                ('scientific_name', models.CharField(max_length=100, null=True)),
                ('sex', models.CharField(max_length=100)),
                ('trait_name', models.CharField(max_length=100)),
                ('trait_value', models.CharField(max_length=100)),
                ('trait_unit', models.CharField(max_length=100)),
            ],
        ),
    ]
