# Generated by Django 3.1.7 on 2021-03-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Edit_Text',
        ),
    ]
