# Generated by Django 3.1.7 on 2021-04-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='json_table',
            name='pdf_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='json_table',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
