# Generated by Django 3.1.7 on 2021-04-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20210402_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='json_table',
            name='page_number',
            field=models.IntegerField(null=True),
        ),
    ]
