# Generated by Django 3.1.7 on 2021-04-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_json_table_page_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='json_table',
            name='table',
            field=models.FileField(max_length=500, upload_to='json/'),
        ),
    ]
