# Generated by Django 3.1.7 on 2021-04-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_auto_20210405_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trait_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_id', models.IntegerField(null=True)),
                ('trait_name', models.CharField(max_length=100)),
                ('trait_value', models.CharField(max_length=100)),
                ('trait_unit', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
            ],
        ),
    ]
