# Generated by Django 3.1.7 on 2021-04-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_trait_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait_table',
            name='scientific_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
